version: '3.9'
services:
  app:
    container_name: php-apache
    restart: unless-stopped
    build:
      context: .
      dockerfile: _docker/php-apache/Dockerfile
    volumes:
      - .:/var/www/domains
      - ./_docker/config/apache2.conf:/etc/apache2/apache2.conf
      - ./_docker/config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${APP_EXTERNAL_PORT:-80}:80"
    environment:
      - FIRST_DOMAIN=${FIRST_DOMAIN}
      - SECOND_DOMAIN=${SECOND_DOMAIN}
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: maria-mysql
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    ports:
      - "${PMA_EXTERNAL_PORT}:80"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6.0
    volumes:
      - ./redis-data:/data